DROP TABLE dim_race CASCADE CONSTRAINTS;
DROP TABLE dim_driver CASCADE CONSTRAINTS;
DROP TABLE dim_constructor CASCADE CONSTRAINTS;

CREATE TABLE dim_driver (
    driver_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id VARCHAR2(50) NOT NULL,
    permanent_number NUMBER,
    code VARCHAR2(10),
    given_name VARCHAR2(100) NOT NULL,
    family_name VARCHAR2(100) NOT NULL,
    date_of_birth DATE,
    nationality VARCHAR2(100),
    driver_url VARCHAR2(500),
    CONSTRAINT uk_dim_driver_driver_id UNIQUE (driver_id)
);

CREATE TABLE dim_constructor (
    constructor_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    constructor_id VARCHAR2(50) NOT NULL,
    constructor_name VARCHAR2(150) NOT NULL,
    nationality VARCHAR2(100),
    constructor_url VARCHAR2(500),
    CONSTRAINT uk_dim_constructor_constructor_id UNIQUE (constructor_id)
);

CREATE TABLE dim_race (
    race_sk NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    season NUMBER NOT NULL,
    round_number NUMBER NOT NULL,
    race_name VARCHAR2(150) NOT NULL,
    race_date DATE,
    race_time VARCHAR2(20),
    race_url VARCHAR2(500),
    circuit_id VARCHAR2(100),
    circuit_name VARCHAR2(150),
    locality VARCHAR2(150),
    country VARCHAR2(150),
    CONSTRAINT uk_dim_race_season_round UNIQUE (season, round_number)
);